### ISSUE TITLE
1.4.0 Breaks Sinatra::register with the block

### ISSUE THREAD

**Issue by aportnov** [sinatra/sinatra#683]
Looks like after upgrading to Sinatra 1.4.0 I am no longer able to register extensions by passing a block to Sinatra::register

This works in 1.3.5:

Sinatra::register do  
   before do
         response['Access-Control-Allow-Methods'] = 'GET, POST'
   end  
end

in 1.4.0 I am getting the following error:

NoMethodError: undefined method `before' for #Module:0x3cc489a0
         (root) at /Users/xxxxxx/dev/projects/app.rb:105
    module_exec at org/jruby/RubyModule.java:2322
     initialize at org/jruby/RubyModule.java:1832
       register at /Users/xxxxxx/.rvm/gems/jruby-1.7.2@xxx/gems/sinatra-1.4.0/lib/sinatra/base.rb:1497
       register at /Users/xxxxxx/.rvm/gems/jruby-1.7.2@xxx/gems/sinatra-1.4.0/lib/sinatra/base.rb:1869
       register at /Users/xxxxxx/.rvm/gems/jruby-1.7.2@xxx/gems/sinatra-1.4.0/lib/sinatra/base.rb:1931

Looks like it is because of the change to the main.rb 

line 30:
extend Sinatra::Delegator
vs.
include Sinatra::Delegator  that works.
